name: Rakib-Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create fake font config folder
        run: |
          mkdir -p /tmp/fonts
          echo "<?xml version='1.0'?>" > /tmp/fonts/fonts.conf
          echo "<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>" >> /tmp/fonts/fonts.conf
          echo "<fontconfig></fontconfig>" >> /tmp/fonts/fonts.conf
          echo "FONTCONFIG_PATH=/tmp/fonts" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Start Rakib-Bot
        run: npm start
